name: MATLAB Tests
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, matlab]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        matlab -batch "runtests('YourTestScript.m')"
