name: MATLAB Tests
on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |    
        export DISPLAY=:99
        Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & /usr/local/MATLAB/2020a/bin/matlab -nodesktop -nosplash -r "runtests('./test/testAll_ghActions.m');exit;"

        

