name: MATLAB Tests
on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |         
        /home/aaron/Documents/Matlab/bin/matlab -nodesktop -nosplash -r "runtests('./test/testAll_ghActions.m');exit;"

        

