name: MATLAB Tests
on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: [self-hosted, King]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        matlab -batch "runtests('test/testAll.m')"
