name: MATLAB Tests
on: 
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        sudo apt-get install -y xvfb
        export DISPLAY=:99
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        /usr/local/MATLAB/R2020a/bin/matlab -nodesktop -nosplash -r "runtests('./test/testAll.m');exit;"
        

