name: MATLAB Tests
on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    steps:
    - uses: actions/checkout@v2

    - name: Clone COBRA Toolbox
      run: |
        git clone https://github.com/opencobra/cobratoolbox.git cobratoolbox

    - name: Set up MATLAB
      uses: matlab-actions/setup-matlab@v1
      with:
        release: R2024a  # Specify the MATLAB release

    - name: Run MATLAB tests
      uses: matlab-actions/run-command@v1
      with:
        command: |
          run('cobratoolbox/initCobraToolbox.m'); 
          changeCobraSolver('glpk', 'LP'); 
          diary('test_results.txt'); 
          testOptimizeCbModel; 
          diary off;

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test_results.txt
